/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 low_poly_rock.glb -t -T 
Files: low_poly_rock.glb [2.78MB] > low_poly_rock-transformed.glb [107.83KB] (96%)
Author: MMandali (https://sketchfab.com/rasmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-rock-491da500467d4dd08fd9cba89c919f64
Title: Low Poly Rock
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Cube: THREE.MeshStandardMaterial
  }
}

export const Low_poly_rock = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('./assets/low_poly_rock-transformed.glb') as GLTFResult;
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Cube} />
    </group>
  );
});

